### DISCUSSION TITLE
¿How to configure environment variables for backups in production mode?

### DISCUSSION THREAD

**Discussion by pleirb** [Tecnativa/doodba-copier-template#452] [Q&A] [answered]
This common.yaml file references a backup container generated by copier:

```
backup:
    image: ghcr.io/tecnativa/docker-duplicity-postgres:latest
    hostname: backup.domain.com
    init: true
    environment:
      DB_VERSION: "15"
      DBS_TO_INCLUDE: "^prod"
      DST: "webdavs://user@domain.com@webdav.pcloud.com/path/to/backup"
      EMAIL_FROM: "user@domain.com"
      EMAIL_TO: "user@domain.com"
      JOB_500_WHAT: dup full $$SRC $$DST
      JOB_500_WHEN: weekly
      JOB_800_WHAT: dup --force remove-older-than 1W $$DST
      JOB_800_WHEN: weekly
      PGDATABASE: *dbname
      PGUSER: *dbuser
      SMTP_HOST: smtplocal
      TZ: "America/Montevideo"
    volumes:
      - backup_cache:/root:z
      - filestore:/mnt/backup/src/odoo:z
```

And this is a custom example of .docker/backup.env:

```
#jinja2: lstrip_blocks: "true", trim_blocks: "true"
PASSPHRASE=password


# This FTP password is also used for other types of remote backups such as webdavs
FTP_PASSWORD=password
# Variables that can be used with 15min hourly daily weekly or monthly modes in the JOB_*_WHEN configuration set in common.yaml backup service
# Every 15 minutes
CRONTAB_15MIN=*/15 * * * *
# Hourly
CRONTAB_HOURLY=0 * * * *
# Run at 10, 14 and 18 hours from Monday to Friday
CRONTAB_DAILY=0 10,14,18 * * MON-FRI
# Every Sunday at 10:00 p.m.
CRONTAB_WEEKLY=0 22 * ​​* SUN
# On the 1st of each month at 5:00
CRONTAB_MONTHLY=0 5 1 * *
```

It must be taken into account that the backup time that will remain in the remote destination will always be UTC. However, the hours to be used in CRONTAB can be those of your time zone if the TZ variable was configured correctly.
On the other hand, we must understand that the CRONTAB environment variables have a default value that if we change it we can change the behavior of 15min hourly daily weekly or monthly of our JOB_*_WHEN
We can put these variables directly in ./docker/backup.env and we can help ourselves build them with this tool: https://crontab.guru/
Also note that the FTP_PASSWORD variable is convenient to use so that email reports do not publish the password of our remote destination. We might be tempted to use a destination path like this: `webdavs://user@domain.com:password@webdav.pcloud.com/path/to/backup`
Curiously, FTP_PASSWORD also works for other types of services such as Webdavs, which is used by some cloud storage services such as Pcloud
