### ISSUE TITLE
How to copy odoo code from existing projects to save time and bandwidth?

### ISSUE THREAD

**Issue by obayit** [Tecnativa/doodba-copier-template#174]
In short:
I tried to copy odoo 12.0 code from a previous project on a new one, then ran `invoke git-aggregate` normally. But after starting the production environment it gives the error `FileNotFoundError: [Errno 2] No such file or directory`, the `/opt/odoo/custom/src/odoo` directory is not included in the container!

Long version:
I created a new project with the following steps:

1. `copier copy gh:Tecnativa/doodba-copier-template heavyprod`
2. `invoke img-pull img-build --pull`
3. changed the repos.yaml to the following (official odoo):
```
# See https://github.com/Tecnativa/doodba#optodoocustomsrcreposyaml
./odoo:
  defaults:
    # Shallow repositories ($DEPTH_DEFAULT=1) are faster & thinner
    # You may need a bigger depth when merging PRs (use $DEPTH_MERGE
    # for a sane value of 100 commits)
    depth: $DEPTH_DEFAULT
  remotes:
    odoo: https://github.com/odoo/odoo.git
  target: odoo $ODOO_VERSION
  merges:
    - odoo $ODOO_VERSION
    # Example of a merge of the PR with the number <PR>
    # - oca refs/pull/<PR>/head
```
4. copied existing odoo repo from previous working project with:
`rsync -av ../proj1/odoo/custom/src/odoo odoo/custom/src/`
5 ran `invoke git-aggregate`
6 started production with `docker-compose -f prod.yaml up -d`

After that when I run `invoke logs` I see the following:
```
db_1                      | 2020-11-11 07:04:26.492 GMT [1] LOG:  starting PostgreSQL 13.0 on x86_64-pc-linux-musl, compiled by gcc (Alpine 9.3.0) 9.3.0, 64-bit
db_1                      | 2020-11-11 07:04:26.492 GMT [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
db_1                      | 2020-11-11 07:04:26.492 GMT [1] LOG:  listening on IPv6 address "::", port 5432
db_1                      | 2020-11-11 07:04:26.609 GMT [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
db_1                      | 2020-11-11 07:04:26.619 GMT [21] LOG:  database system was shut down at 2020-11-11 07:02:22 GMT
db_1                      | 2020-11-11 07:04:26.631 GMT [1] LOG:  database system is ready to accept connections
odoo_1                    | doodba INFO: Merging found configuration files in /opt/odoo/auto/odoo.conf
odoo_1                    | doodba INFO: Executing /usr/local/bin/odoo
odoo_1                    | Traceback (most recent call last):
odoo_1                    |   File "/opt/odoo/common/entrypoint", line 75, in <module>
odoo_1                    |     os.execvp(extra_command[0], extra_command)
odoo_1                    |   File "/usr/local/lib/python3.5/os.py", line 615, in execvp
odoo_1                    |     _execvpe(file, args)
odoo_1                    |   File "/usr/local/lib/python3.5/os.py", line 639, in _execvpe
odoo_1                    |     exec_func(file, *argrest)
odoo_1                    | FileNotFoundError: [Errno 2] No such file or directory
```

Also inspecting the directory `/opt/odoo/custom/src` with `docker-compose -f prod.yaml run -l traefik.enable=false --rm odoo ls -la /opt/odoo/custom/src/` gives the following output:
```
Starting heavyprod_db_1 ... done
doodba INFO: Waiting until postgres is listening at db...
doodba INFO: Linking all addons from /opt/odoo/custom/src/addons.yaml in /opt/odoo/auto/addons
doodba INFO: Generating /opt/odoo/auto/odoo.conf file. Overriding any existing...
doodba INFO: Merging found configuration files in /opt/odoo/auto/odoo.conf
doodba INFO: Executing ls -la /opt/odoo/custom/src/
total 16
drwxr-x--- 1 root odoo 4096 Nov 11 06:15 .
drwxr-x--- 1 root odoo 4096 Nov 11 06:40 ..
-rw-r----- 1 root odoo    0 Nov 11 06:11 addons.yaml
drwxr-x--- 1 root odoo 4096 Nov 11 06:15 private
-rw-r----- 1 root odoo  589 Nov 11 06:11 repos.yaml
```
There is no `odoo` directory!
