### ISSUE TITLE
TURN docker service

### ISSUE THREAD

**Issue by giarve** [Tecnativa/doodba-copier-template#537]
I have been lately playing with custom TURN servers for when direct connection is not possible to be established in discuss for calls or videocalls.

A service like this can be used with env variables to make up for a relay server:

```
services:
  coturn:
    image: docker.io/coturn/coturn
    environment:
      - DETECT_EXTERNAL_IP=yes
      - DETECT_RELAY_IP=yes
    command: "--fingerprint --lt-cred-mech --user odooice:1234strongpass --realm odooprojectname"
    network_mode: "host"
```

Mind that the host will probably use more resources, but it allows connections that would not be possible in the past.

No need to use Twilio:
https://www.odoo.com/documentation/16.0/applications/productivity/discuss/ice_servers.html#define-a-list-of-custom-ice-servers

You can also test it with https://webrtc.github.io/samples/src/content/peerconnection/trickle-ice/
